- .gitignore
- backend/.gitignore
- electron/.gitignore
- ui/.gitignore
1. Created a comprehensive root-level .gitignore file that covers all project components (backend, ui, electron).
2. Organized ignore patterns into clear categories: general, IDEs/editors, Node.js, Python, build/distribution, testing, logs, environment files, application-specific, and large media files.
3. Removed duplicate entries and consolidated similar patterns for improved maintainability.
4. Ensured coverage for all aspects of the project, including framework-specific ignores (e.g., Angular, Electron).
> Chore: Refactor .gitignore files

- ui/src/app/components/core/search-input/search-input.component.ts
- ui/src/app/components/document-listing/document-listing.component.ts
This PR introduces functionality to automatically clear the search input field whenever the requirement changes. This ensures the search state remains relevant to the selected requirement and prevents confusion caused by lingering search terms.
> feat: add clear search functionality to search input component

- .github/workflows/sync-github-to-gitlab.yml
feat(ci): Add GitHub to GitLab sync workflow
- Configured automated sync from GitHub main branch to GitLab
- Set up SSH authentication and Git identity for secure syncing
> feat(ci): Add GitHub to GitLab sync workflow.

- .github/workflows/sync-github-to-gitlab.yml
feat(ci): Updated GitHub to GitLab sync workflow to qa environment.
> feat(ci): Updated GitHub to GitLab sync workflow to qa environment.

- backend/llm/prompts/chat/update_requirement.jinja2
- backend/llm/prompts/chat/update_user_story_task.jinja2
Refined **update_requirement** and **update_user_story_task** prompts to avoid code snippets in ai chat responses
> refine: prompt refinement to avoid code snippets in ai chat responses

- .github/workflows/sync-github-to-gitlab.yml
Fix: Resolve pipeline issues for merging into QA on GitLab repo
> Fix: Resolve pipeline issues for merging into QA on GitLab repo

- electron/package.json
- ui/package.json
- ui/src/environments/environment.development.ts
- ui/src/environments/environment.prod.ts
- ui/src/environments/environment.ts
chore: updated the version to 1.9.6 with bug-fixes and minor UI enhancements
> chore: updated the version to 1.9.6

- backend/api/chat_api.py
- backend/llm/prompts/chat/improve_suggestions.jinja2
- backend/schemas/chat_schema.py
- ui/src/app/components/ai-chat/ai-chat.component.html
- ui/src/app/components/ai-chat/ai-chat.component.ts
- ui/src/app/model/interfaces/chat.interface.ts
**Recurring suggestions for AI Chat**
Changes:
- Added recurring suggestions
- Regenerate suggestions while description gets updated
- Auto scroll down after suggestions are generated
> Recurring suggestions for AI Chat

- .changeset/neat-eels-bake.md
- ui/src/app/components/ai-chat/ai-chat.component.html
- ui/src/app/constants/app.constants.ts
- ui/src/app/pages/app-info/app-info.component.html
- ui/src/app/pages/edit-user-stories/edit-user-stories.component.ts
- Fix: Chat history is disappearing in User story
- Fix: Task chat is breaking due to payload validation failure
- Enhancement: Jira Prequisite Message
- Enhancement: Suggestions appear horizontal when chat history is not empty
> Story/Task bug fixes and UI enhancements

- .changeset/green-days-jump.md
- .changeset/sour-parrots-vanish.md
- backend/llm/prompts/09_add_business_process.jinja2
- backend/llm/prompts/10_update_business_process.jinja2
Update the business process add and update prompt to not include marketing, promotional or summarizing content
-   [x] 💅 Enhancement (non-breaking change which enhances a feature)
> feat: Update business process add and update prompts

- .changeset/smart-spies-return.md
- ui/src/app/pages/business-process/business-process.component.ts
keep the user on the same page after business process update
-   [x] 💅 Enhancement (non-breaking change which enhances a feature)
> feat: keep the user on the same page after business process update

- .changeset/chubby-candies-clean.md
- ui/src/app/pages/edit-solution/edit-solution.component.html
- ui/src/app/pages/edit-solution/edit-solution.component.ts
- ui/src/app/pages/edit-user-stories/edit-user-stories.component.html
- ui/src/app/pages/edit-user-stories/edit-user-stories.component.ts
- ui/src/app/pages/tasks/add-task/add-task.component.html
- ui/src/app/pages/tasks/add-task/add-task.component.ts
- Checkbox to Button for Enhance with AI for Root Requirements, User Stories and Tasks
- Verbiage change "Expand" to "Enhance"
> Refactor: Checkbox to Button for Expand with AI

- .changeset/blue-parrots-brush.md
- ui/src/app/pages/edit-solution/edit-solution.component.html
- ui/src/app/pages/edit-user-stories/edit-user-stories.component.html
- ui/src/app/pages/tasks/add-task/add-task.component.html
- UI Fix for multi file upload and alignment
> fix: adjust layout alignment for upload components

- .changeset/curvy-impalas-buy.md
- .changeset/green-garlics-cheer.md
- .changeset/shy-towns-kick.md
- .changeset/upset-hands-hang.md
- .changeset/whole-dancers-cry.md
- CHANGELOG.md
- electron/package.json
- package.json
- ui/package.json
- ui/src/environments/environment.development.ts
- ui/src/environments/environment.prod.ts
- ui/src/environments/environment.ts
> Prepare for Release (v1.9.9)

- .changeset/fair-lines-guess.md
- ui/src/app/components/ai-chat/ai-chat.component.html
- ui/src/app/components/core/breadcrumbs/breadcrumbs.component.html
- ui/src/app/components/core/button/button.component.html
- ui/src/app/components/core/input-field/input-field.component.html
- ui/src/app/components/core/textarea-field/textarea-field.component.html
- ui/src/app/components/layout/header/header.component.html
- ui/src/app/components/multi-upload/multi-upload.component.html
- ui/src/app/components/multi-upload/multi-upload.component.ts
- ui/src/app/pages/edit-solution/edit-solution.component.html
- ui/src/app/pages/edit-user-stories/edit-user-stories.component.html
- ui/src/app/pages/tasks/add-task/add-task.component.html
| before | after |
|--------|--------|
| ![CleanShot 2025-03-03 at 22 46 58@2x](https://github.com/user-attachments/assets/1cffeecc-be79-49b0-a325-1616fd9c1f31) | ![CleanShot 2025-03-03 at 22 43 42@2x](https://github.com/user-attachments/assets/cd55f5fc-21f3-44ef-94e5-5e2e7cae9a40) |
> refactor: Improve UI consistency and styling across upload code components

- .changeset/upset-dancers-heal.md
- ui/src/app/services/export/strategies/brd-export.strategy.ts
- ui/src/app/services/export/strategies/nfr-export.strategy.ts
- ui/src/app/services/export/strategies/uir-export.strategy.ts
- ui/src/app/services/export/strategies/user-stories-export.strategy.ts
fix: names of export of brd, nfr, uir and user-stories.
> fix: names of export of brd, nfr, uir and user-stories.

- .gitignore
- electron/.gitignore
- ui/.gitignore
- ui/package-lock.json
Added package-lock.json for UI to resolve the pipeline error
> fix: Added package-lock.json for UI

- .changeset/huge-monkeys-scream.md
- backend/env.sh
- backend/llm/__init__.py
- backend/llm/providers/gemini_handler.py
- backend/llm/providers/ollama_handler.py
- backend/requirements.txt
- backend/utils/env_utils.py
- electron/package-lock.json
- ui/src/app/constants/llm.models.constants.ts
Added support to the following models
- Gemini
- Ollama (Backend alone)
> Added Gemini and Ollama (Backend) support

- backend/api/common_api.py
Added the hello api back since it is used by ecs for health check
> fix: Added the hello api back since it is used by ecs for health check

- ui/src/app/pages/edit-user-stories/edit-user-stories.component.ts
- ui/src/app/services/export/strategies/prd-export.strategy.ts
- ui/src/app/services/export/strategies/user-stories-export.strategy.ts
Fixed and changed the following:
- Fixed unknown text in user story description update toaster
- Removed parent id appended for User Story and Task in xlsx
[AI chat app_prd_export_1742388509773.xlsx](https://github.com/user-attachments/files/19341013/AI.chat.app_prd_export_1742388509773.xlsx)
> fix: Fixed unknown text in user story desc update and Removed parent id appended in PRD export

- electron/file-system.utility.js
This PR fixes an issue where the application couldn't load a directory at all if any solution file was corrupted or invalid.
> fix: handle corrupted/invalid solution files during directory loading

- .changeset/two-actors-matter.md
- ui/src/app/pages/login/login.component.ts
Fixed user information getting cleared in login screen
> Fixed user information getting cleared in login screen

- electron/prompts/context/bp.ts
- electron/prompts/requirement/add.ts
- electron/prompts/requirement/chat.ts
- electron/prompts/requirement/update.ts
- electron/utils/get-context.ts
- Added BP Type to the enum and context
> Fix: Added BP type

- .github/workflows/release.yml
> fix: fixed the intent issue in release.yml

- .github/workflows/build.yml
> fix: removed platform directory for darwin in the s3 folder struture

- .github/workflows/build.yml
- .github/workflows/notify.yml
- .github/workflows/release.yml
Add PostHog configuration variables to workflows deriving from release.yml
> fix: add PostHog configuration variables to workflows

- .github/workflows/build.yml
> fix: fixed .env overriding issue

- .changeset/eager-facts-flash.md
- .changeset/loud-corners-nail.md
- .changeset/puny-ends-trade.md
- .changeset/sour-trees-enjoy.md
- .changeset/two-actors-matter.md
- CHANGELOG.md
- electron/package-lock.json
- electron/package.json
- package.json
- ui/package-lock.json
- ui/package.json
- ui/src/environments/environment.development.ts
- ui/src/environments/environment.prod.ts
- ui/src/environments/environment.ts
- Update docs for Release (v2.0.0)
> Prepare for Release (v2.0.0)

- .github/workflows/create-release.yml
> Fix: Windows latest.yml path in release workflow

- .github/workflows/create-release.yml
fix: removed count from create-release
> fix: removed count from create-release

- .changeset/late-phones-serve.md
- electron/services/llm/index.ts
- electron/services/llm/llm-types.ts
- electron/services/llm/providers/ollama.ts
- electron/services/llm/providers/openrouter.ts
- ui/src/app/components/settings/settings.component.ts
- ui/src/app/constants/llm-provider-config.ts
- ui/src/app/constants/llm.models.constants.ts
- ui/src/app/pages/app-info/app-info.component.html
- ui/src/app/pages/app-info/app-info.component.ts
- ui/src/app/services/analytics/managers/posthog-analytics.manager.ts
- ui/src/app/store/llm-config/llm-config.state.ts
- Openrouter support & Ollama support
- Refactor existing getModelOptions to function for better flexibility
- Bedrock KB override toggle only when bedrock credentials are present
- Added active provider to PostHog tracking
> Openrouter & Ollama Integration

- .changeset/late-phones-serve.md
- .changeset/ready-swans-decide.md
- CHANGELOG.md
- electron/package-lock.json
- electron/package.json
- package.json
- ui/package-lock.json
- ui/package.json
- ui/src/environments/environment.development.ts
- ui/src/environments/environment.prod.ts
- ui/src/environments/environment.ts
> Prepare for release (v2.1.0)

- electron/api/core/get-suggestions.ts
- electron/api/feature/story/add.ts
- electron/api/feature/story/chat.ts
- electron/api/feature/story/create.ts
- electron/api/feature/story/update.ts
- electron/api/feature/task/add.ts
- electron/api/feature/task/create.ts
- electron/api/feature/task/update.ts
- electron/api/requirement/add.ts
- electron/api/requirement/business-process/add.ts
- electron/api/requirement/business-process/update.ts
- electron/api/requirement/chat.ts
- electron/api/requirement/update.ts
- electron/api/solution/create.ts
- electron/api/visualization/flowchart.ts
- electron/helper/constants.ts
- electron/utils/trace-builder.ts
- Provisioned more specific langfuse traces.
> Refactor: Traces Update

- ui/src/app/pages/business-process/business-process.component.ts
- ui/src/app/pages/edit-solution/edit-solution.component.ts
- ui/src/app/pages/edit-user-stories/edit-user-stories.component.ts
- ui/src/app/pages/user-stories/user-stories.component.ts
> Fix: Mark Form Untouched and Pristine

- .github/workflows/build.yml
- .github/workflows/create-release.yml
Fix: Include Windows exe and blockmap to release assets
> Fix: Include Windows exe and blockmap to release assets

- .changeset/clear-donkeys-glow.md
- .changeset/cold-toys-move.md
- .changeset/four-pumas-write.md
- .changeset/weak-sloths-wink.md
- CHANGELOG.md
- README.md
- electron/package-lock.json
- electron/package.json
- package.json
- ui/package-lock.json
- ui/package.json
- ui/src/environments/environment.development.ts
- ui/src/environments/environment.prod.ts
- ui/src/environments/environment.ts
- Update docs for Release (v2.1.1)
> Prepare for Release (v2.1.1)

- .github/workflows/create-release.yml
> fix: fixed windows yml file copy issue

- .github/workflows/build.yml
- .github/workflows/create-release.yml
- README.md
> Fix: Sed Issue

- .changeset/angry-sloths-hope.md
- ui/src/app/components/document-listing/document-listing.component.html
- ui/src/app/components/document-listing/document-listing.component.ts
- ui/src/app/export-dropdown/export-dropdown.component.html
- ui/src/app/export-dropdown/export-dropdown.component.spec.ts
- ui/src/app/export-dropdown/export-dropdown.component.ts
- ui/src/app/pages/tasks/task-list/task-list.component.ts
- ui/src/app/pages/user-stories/user-stories.component.html
- ui/src/app/pages/user-stories/user-stories.component.ts
- Regenerate Tasks on cancel
- Font inconsistency in Export Menu (Changes to tailwind from angular material)
> Fix: Regenerate tasks on cancel and Menu fix

- electron/package.json
- ui/src/app/components/core/slider/slider.component.ts
- ui/src/app/constants/app.constants.ts
- ui/src/app/pages/create-solution/create-solution.component.ts
The app is unable to open due to the library conflict. Fixed the issue by adding the libs to the electron/package.json. Also, fixed validation issue in Create Solution
> fix: Electron app library fix

- .changeset/orange-comics-spend.md
- ui/src/app/components/settings/settings.component.html
- Disable search for provider dropdown
> Fix: Disable search for provider dropdown

- ui/src/app/components/mcp-integration-configurator/mcp-integration-configurator.component.html
- ui/src/app/components/settings/settings.component.html
This PR enhances the visual feedback of the MCP server component using indigo styling for a more consistent UI experience.  
It also refactors the Settings component by simplifying section titles, improving readability.
> feat(ui): enhance MCP server card with indigo styling and simplify settings section titles

- .changeset/cute-papers-repair.md
- .changeset/fluffy-snakes-create.md
- .changeset/free-points-eat.md
- .changeset/giant-wombats-show.md
- .changeset/lovely-bars-tell.md
- .changeset/shaggy-bananas-fry.md
- CHANGELOG.md
- electron/package-lock.json
- electron/package.json
- package.json
- ui/package-lock.json
- ui/package.json
- ui/src/environments/environment.development.ts
- ui/src/environments/environment.prod.ts
- ui/src/environments/environment.ts
Release version v2.3.0 updates
-   [X] 📚 Documentation update
> Release version v2.3.0 updates

- .changeset/quick-dryers-follow.md
- electron/agentic/suggestion-workflow/index.ts
- electron/agentic/suggestion-workflow/nodes.ts
- electron/agentic/suggestion-workflow/prompts/research-information.ts
- electron/agentic/suggestion-workflow/prompts/summarize-research.ts
- electron/agentic/suggestion-workflow/prompts/utils.ts
- electron/agentic/suggestion-workflow/state.ts
- electron/agentic/suggestion-workflow/types.ts
- electron/api/core/get-suggestions.ts
- electron/prompts/core/improved-suggestions.ts
- electron/schema/core/get-suggestions.schema.ts
- electron/schema/helper/bedrock.options.schema.ts
- ui/src/app/components/ai-chat/ai-chat.component.ts
- ui/src/app/model/interfaces/chat.interface.ts
This PR refactors the suggestion generation functionality to use the agentic workflow pattern.
Key changes:
- Create dedicated suggestion workflow implementation in `electron/agentic/suggestion-workflow/`
- Update `get-suggestions.ts` to use the new workflow
This refactoring follows the same pattern as the task workflow implementation, making the codebase more consistent and maintainable.
> refactor(suggestions): Refactor suggestion generation to use agentic workflow pattern

- .changeset/lazy-plants-help.md
- ui/src/app/components/core/input-field/input-field.component.html
- ui/src/app/components/core/input-field/input-field.component.ts
- ui/src/app/components/core/slider/slider.component.html
- ui/src/app/components/custom-accordion/custom-accordion.component.html
- ui/src/app/components/toggle/toggle.component.html
- ui/src/app/constants/app.constants.ts
- ui/src/app/pages/apps/apps.component.html
- ui/src/app/pages/create-solution/create-solution.component.html
> feat: Enhance Create Solution Page Design

- electron/services/observability/observability.manager.ts
Added provider and model information to trace metadata in ObservabilityManager.
> feat: Add LLM provider and model metadata to traces

- electron/app.ts
- ui/src/app/components/core/breadcrumbs/breadcrumbs.component.html
- ui/src/app/components/layout/header/header.component.html
- ui/src/app/components/layout/header/header.component.ts
> refactor(header): Update header layout and improve breadcrumb styling

- electron/app.ts
- ui/src/app/components/layout/header/header.component.ts
- ui/src/app/electron-bridge/electron.interface.ts
- ui/src/app/electron-bridge/electron.service.ts
add platform detection to Electron service and update header component
> feat(electron): add platform detection to Electron service and update header component

- electron/app.ts
- electron/preload.ts
- ui/src/app/components/layout/header/header.component.ts
- ui/src/app/electron-bridge/electron.interface.ts
- ui/src/app/electron-bridge/electron.service.ts
refactor: Add platform detection directly in preload script
> refactor: Add platform detection directly in preload script

- electron/agentic/create-solution-workflow/nodes.ts
- electron/agentic/task-workflow/nodes.ts
- electron/agentic/user-story-workflow/nodes.ts
refactor: changed research node type from thinking to action
> refactor: changed research node type from thinking to action

- docs/docs/current/JIRA-README.md
- docs/docs/current/aws-bedrock-kb-configuration.md
Update image paths in JIRA and AWS Bedrock KB documentation.
> fix: update image paths in JIRA and AWS Bedrock KB documentation

- ui/src/app/components/document-listing/document-listing.component.ts
- ui/src/app/components/pmo-integration-modal/pmo-integration-modal.component.html
- ui/src/app/components/pmo-integration-modal/pmo-integration-modal.component.ts
- ui/src/app/config/pmo-modal.config.ts
- ui/src/app/integrations/ado/ado.service.ts
- ui/src/app/services/pmo-integration/pmo-service.interface.ts
- Loaded current PRD into the PMO modal component to perform push operation for the selected workitems.
> feat: loaded current PRD's into hierarchy structure for push operation to ADO

- electron/api/core/verify-config.ts
- ui/src/app/components/settings/settings.component.ts
- ui/src/app/pages/user-stories/user-stories.component.ts
- ui/src/app/store/llm-config/llm-config.state.ts
> chore: removed console logs

- ui/src/app/app-routing.module.ts
- ui/src/app/pages/test-cases/test-case-detail/test-case-detail.component.ts
- ui/src/app/pages/test-cases/test-case-home/test-case-home.component.html
- ui/src/app/pages/test-cases/test-case-home/test-case-home.component.ts
- ui/src/app/pages/test-cases/test-case-list/test-case-list.component.ts
Fixed:
- When the user tries to add an empty field in post condition, it is getting added as an empty bulletin
- When the user tries to save the test case by leaving the description as empty, it is not giving any warning toaster
- The breadcrumb navigation bar is not displaying the actual tree structure
- Search bar in the Test case page is breaking while searching
- Remove the Go To Solution button from the Test Cases page
-   [ ] Changes are limited to a single feature, bugfix or chore (split larger changes into separate …
> Test Case Fixes

- .changeset/tricky-teeth-design.md
- docs/docs/current/JIRA-README.md
- electron/README.md
- electron/handlers/jira-handler.ts
- ui/src/app/integrations/jira/jira.utils.ts
fix: Updated Jira callback port to 12345, as Filewall continues to block the port.
> fix: Updated jira callback port to 12345

- .changeset/cold-schools-check.md
- ui/src/app/pages/edit-user-stories/edit-user-stories.component.ts
> regeneration fixed after deletion of us

- ui/src/app/components/document-listing/document-listing.component.html
- ui/src/app/components/inline-edit-prompt/inline-edit-prompt.component.html
- Fixed Inline Edit Cancel and Removed Global Options
> fix: cancel inline edit and remove options

- .changeset/cold-schools-check.md
- .changeset/hip-kids-know.md
- .changeset/smart-worlds-chew.md
- .changeset/tidy-words-love.md
- .changeset/upset-crews-judge.md
- CHANGELOG.md
- electron/package-lock.json
- electron/package.json
- package.json
- ui/package-lock.json
- ui/package.json
- ui/src/environments/environment.development.ts
- ui/src/environments/environment.prod.ts
- ui/src/environments/environment.ts
> Updated to version 2.8.0

- README.md
Strategic Initiative README Update
> Chore: Strategic Initiative README Update

- .changeset/public-buttons-speak.md
- electron/handlers/jira-handler.ts
- ui/src/app/components/core/button/button.component.html
- ui/src/app/components/core/button/button.component.ts
- ui/src/app/components/core/list-item/list-item.component.html
- ui/src/app/components/core/list-item/list-item.component.ts
- ui/src/app/components/document-listing/document-listing.component.html
- ui/src/app/components/document-listing/document-listing.component.ts
- ui/src/app/components/pmo-integration/jira-integration/jira-integration.component.ts
- ui/src/app/model/interfaces/projects.interface.ts
- ui/src/app/services/integration-credentials/integration-credentials.service.ts
- ui/src/app/services/pmo-url/pmo-url.service.ts
Add badge click functionality for opening Jira/ADO links directly from Specifai.  
closes: #301 
> feat: add badge click support for opening Jira/ADO links
