presidio-oss/specif-ai

ui/src/app/constants/app.constants.ts, ui/src/app/pages/edit-solution/edit-solution.component.ts, ui/src/app/store/projects/projects.actions.ts, ui/src/app/store/projects/projects.state.ts
This PR implements a restriction on the deletion of PRD (Product Requirement Document) and BRD (Business Requirement Document) files if they are currently in use by a Business Process (BP). The feature ensures that these documents cannot be deleted when associated with an active business process.
- Added logic to check if PRD or BRD files are associated with any BP before allowing deletion.
- Updated the deletion process to handle these restrictions.
- Enhanced error handling and validation for the deletion process.
- Updated related components to reflect changes in file deletion behavior.
*Screenshot showing the error when attempting to delete a PRD that is in use by a BP.*
=> feat: Add validation for BP file associations for PRDs and BRDs before deletion

ui/src/app/components/document-listing/document-listing.component.html, ui/src/app/components/document-listing/document-listing.component.ts, ui/src/app/pages/apps/apps.component.html, ui/src/app/pages/apps/apps.component.ts, ui/src/app/pages/create-solution/create-solution.component.html, ui/src/app/pages/create-solution/create-solution.component.ts, ui/src/app/pages/tasks/task-list/task-list.component.html, ui/src/app/pages/tasks/task-list/task-list.component.ts, ui/src/app/pages/user-stories/user-stories.component.html, ui/src/app/pages/user-stories/user-stories.component.ts
This PR refactors the navigation methods to use `click` events instead of `routerLink`. The change was made to prevent the `app-button` from being focusable twice. Previously, the `routerLink` was causing the button to be focusable both through the link and the button element, leading to accessibility issues. 
- Replaced `routerLink` with `click` events to resolve the issue of the `app-button` being focusable twice.
=> Refactor navigation methods to use click events instead of routerLink

backend/api/common_api.py, ui/src/app/app.component.ts, ui/src/app/components/llm-settings/llm-settings.component.ts, ui/src/app/components/toaster/toaster.component.html, ui/src/app/components/toaster/toaster.component.ts, ui/src/app/constants/llm.models.constants.ts, ui/src/app/constants/toast.constant.ts, ui/src/app/interceptor/http.interceptor.ts, ui/src/app/pages/login/login.component.ts, ui/src/app/services/auth/auth.service.ts, ui/src/app/services/toaster/toaster.service.ts, ui/src/app/store/llm-config/llm-config.actions.ts, ui/src/app/store/llm-config/llm-config.state.ts
- Added a new endpoint `/api/llm-config/defaults` in the backend to fetch the default `model` and `provider`
- On the application frontend, 
- Remove the default options selected for LLM Provider and Model
- When logged in or re-fresh, Check with existing LLM configuration settings,
- If configuration is valid, use same settings
- If configuration is invalid, set with default configuration settings
- Modified toast message to disappear automatically after 5 seconds
=> refactor: removed default llm provider settings on electron and fetch the default llm provider settings from backend

.github/workflows/sync-github-to-gitlab.yml
Updated .github/workflows/sync-github-to-gitlab.yml to replace references to qa with release/QA.
Modified steps to:
- Fetch release/QA instead of qa.
- Checkout and merge into release/QA branch instead of qa.
- Push final changes to release/QA branch on GitLab.
- Ensured compatibility with GitLab repository structure.
=> feat(ci): Update GitHub Actions to sync with GitLab release/QA branch

electron/package-lock.json, ui/src/app/components/llm-settings/llm-settings.component.ts, ui/src/app/constants/llm.models.constants.ts, ui/src/app/store/llm-config/llm-config.state.ts
fix: set default LLM provider to OPENAI_NATIVE and model to gpt-4o when configuration is missing
Closes #20
=> fix: set default LLM provider to OPENAI_NATIVE and model to gpt-4o when configuration is missing

ui/src/app/components/ai-chat/ai-chat.component.ts
This PR fixes a bug where users could send empty messages by pressing the Enter key in the chat text area. Now, the send button is disabled if the trimmed message is empty, preventing unintended blank messages.
- Trimmed the input before enabling the send button.  
- Disabled the send button when the input is empty or only contains spaces.
=> Fix: Disable Send Button for Empty Messages in Chat

ui/src/app/pages/login/login.component.ts
This update ensures that any unnecessary white spaces in the App URL entered by the user are trimmed before sending it for verification. Previously, extra spaces caused authentication failures. With this fix, the app will now automatically sanitize the input.
=> fix: Trim App URL Before Verification to Prevent Login Failures

.changeset/tall-mice-bow.md, backend/api/solution_api.py, backend/llm/prompts/08_process_flow_chart.jinja2, backend/schemas/businessprocess_schema.py, ui/src/app/model/interfaces/IBusinessProcess.ts, ui/src/app/pages/business-process-flow/business-process-flow.component.ts, ui/src/app/pages/business-process/business-process.component.ts
1. During addition/ updating a business process the attached PRDs and BRDs will not be appended to the business process description
2. PRDs and BRDs are sent as context during the creation of business process flow chart
3. Added process flow diagram examples and guidelines to create flow chart prompt for better responses
-   [ ] I have reviewed [contributor guidelines](https://github.com/presidio-oss/specif-ai/blob/main/CO …
=> Business Process Flow Enhancements

.changeset/better-mugs-bet.md, .changeset/fine-bars-fail.md, .changeset/neat-eels-bake.md, .changeset/sour-parrots-vanish.md, .changeset/tall-mice-bow.md, CHANGELOG.md, package.json
- Updated changelog and deleted the changeset
- Updated version-packages command in the package.json
=> Prepare for release (v1.9.7)

.changeset/eleven-dragons-sink.md, ui/src/app/pages/edit-user-stories/edit-user-stories.component.ts
The chat breaks after editing a user story because a `ReadFile` is performed, which updates the `selectedFileContent` in the global state. This was added to read the updated content and update the user story component accordingly. However, this action overwrites the `selectedFileContent`, which is supposed to hold the PRDxx-base.json content, with the PRDxx-feature.json content. When navigating to the Task page, it tries to access the `requirement` attribute from the PRDxx-base.json content in the `selectedFileContent`. Due to the overwrite, the requirement attribute becomes undefined, causing the chat to break as the payload's attribute is undefined. This PR fixes this issue.
-   [ ] ✨ New feature (non-breaking change which …
=> fix: removing file read operations to avoid state change

.changeset/warm-ravens-wish.md, ui/src/app/pages/create-solution/create-solution.component.ts
This PR addresses an issue where users could create solutions by entering only spaces in required fields (name, description, and technical details). The fix ensures that input validation properly handles whitespace-only entries.
=> fix: Prevent solution creation with spaces-only input

.changeset/public-impalas-invent.md, ui/src/app/pages/edit-solution/edit-solution.component.html, ui/src/app/pages/edit-user-stories/edit-user-stories.component.html, ui/src/app/pages/tasks/add-task/add-task.component.html
- Margin and disable buttons for invalid forms
- Spacing issue between the buttons
=> fix: margin and disable buttons for invalid forms

.changeset/upset-hands-hang.md, ui/src/app/constants/export.constants.ts, ui/src/app/pages/tasks/task-list/task-list.component.ts, ui/src/app/pages/user-stories/user-stories.component.html, ui/src/app/pages/user-stories/user-stories.component.ts, ui/src/app/services/clipboard.service.ts, ui/src/app/services/export/requirement-export-strategy.manager.ts, ui/src/app/services/export/requirement-export.service.ts, ui/src/app/services/export/strategies/base-requirement-export.strategy.ts, ui/src/app/services/export/strategies/bp-export.strategy.ts, ui/src/app/services/export/strategies/brd-export.strategy.ts, ui/src/app/services/export/strategies/export.strategy.ts, ui/src/app/services/export/strategies/nfr-export.strategy.ts, ui/src/app/services/export/strategies/prd-export.strategy.ts, ui/src/app/services/export/strategies/uir-export.strategy.ts, ui/src/app/services/export/strategies/user-stories-export.strategy.ts, ui/src/app/store/user-stories/user-stories.actions.ts, ui/src/app/store/user-stories/user-stories.state.ts
1. Make prd user stories export format consistent with prds export
2.Removed CSV export option when exporting prd user stories
=> feat: make prd user stories export format consistent with prds export

.changeset/whole-dancers-cry.md, ui/src/app/constants/app.constants.ts, ui/src/app/pages/tasks/task-list/task-list.component.html, ui/src/app/pages/tasks/task-list/task-list.component.ts, ui/src/app/pages/user-stories/user-stories.component.html, ui/src/app/pages/user-stories/user-stories.component.ts
After the generation/regeneration of Task/User Stories, a toast message will be shown to indicate success or failure.
=> Feat: Show Success/Failure Message Toast After Task/User Story Generation/Regeneration

.changeset/huge-otters-sneeze.md, electron/file-system.utility.js, ui/src/app/constants/app.constants.ts, ui/src/app/model/interfaces/projects.interface.ts, ui/src/app/pages/business-process/business-process.component.ts, ui/src/app/pages/create-solution/create-solution.component.html, ui/src/app/pages/create-solution/create-solution.component.ts, ui/src/app/pages/tasks/add-task/add-task.component.ts, ui/src/app/pages/tasks/task-list/task-list.component.ts, ui/src/app/pages/user-stories/user-stories.component.ts, ui/src/app/services/app-system/app-system.service.ts, ui/src/app/services/requirement-id.service.ts, ui/src/app/store/projects/projects.state.ts, ui/src/app/store/user-stories/user-stories.state.ts
This PR improves the requirement ID generation system by implementing type-wise counters (e.g., BRD, US, TASK, PRD) at the solution level.
=> refactor: Implement type-wise requirement ID counters in metadata

.changeset/eager-facts-flash.md, backend/llm/prompts/02_update.jinja2, ui/src/app/components/document-listing/document-listing.component.ts
add instruction in requirement update prompt to output only single requirement
LLM was returning array of requirements sometimes instead of single requirement causing the title and requirement to get assigned undefined.
=> fix: add instruction in requirement update prompt to output only single requirement

.changeset/puny-ends-trade.md, ui/src/app/pages/tasks/add-task/add-task.component.ts
subscribe to current user story in add-task component without this the add/ update task with ai is failing.
=> fix: subscribe to current user story in add-task component

electron/schema/requirement/add.schema.ts, electron/schema/requirement/chat.schema.ts, electron/schema/requirement/update.schema.ts
- Add 'BP' requirement type to requirement schema enums
=> Add 'BP' requirement type to requirement schema enums

ui/src/app/components/settings/settings.component.ts
Fix: config form handling not taking new input on top of store inputs
=> Fix: Config form handling not taking new input on top of store inputs

electron/db/schema.ts, electron/drizzle/0001_slim_talisman.sql, electron/drizzle/meta/0001_snapshot.json, electron/drizzle/meta/_journal.json
Updated the Drizzle schema to include new tables and standardised common columns (e.g., `createdAt`, `updatedAt`, `isDeleted`). This improves consistency and scalability across the backend database structure.
-   [ ] 🐛 Bug fix (non-breaking change which fixes an issue)  
-   [x] ✨ New feature (non-breaking change which adds functionality)  
=> chore: update database schema with new tables and common columns for improved structure

.changeset/clear-crews-drum.md, electron/api/solution/create.ts, ui/src/app/pages/create-solution/create-solution.component.html, ui/src/app/pages/create-solution/create-solution.component.ts
Fixed a bug where solutions were being created even when the `cleanSolution` toggle was enabled. The toggle logic has been updated to respect the `cleanSolution` flag and prevent unintended creation.
=> fix: prevent solution creation when cleanSolution is true

.changeset/orange-cameras-throw.md, ui/src/app/pages/business-process/business-process.component.ts, ui/src/app/pages/edit-solution/edit-solution.component.ts, ui/src/app/pages/edit-user-stories/edit-user-stories.component.ts
Reset `Form` state using `markAsPristine()` and `markAsUntouched()` to ensure that `dirty && touched` checks return false after form submission. This prevents an unintended discard popup when adding.
-   [x] 🐛 Bug fix (non-breaking change which fixes an issue)  
-   [ ] ✨ New feature (non-breaking change which adds functionality)  
=> fix: reset form state to prevent redirect issue on add

.changeset/lemon-donkeys-create.md, ui/src/app/components/core/app-select/app-select.component.html, ui/src/app/components/core/app-select/app-select.component.ts, ui/src/app/components/settings/settings.component.html
Added a "Clear" button to the provider select option on the settings page. This allows users to easily reset their selection without needing to manually deselect or reload the page. 
-   [ ] 🐛 Bug fix (non-breaking change which fixes an issue)  
-   [x] ✨ New feature (non-breaking change which adds functionality)  
-   [x] I have reviewed [contributor guidelines](https://github.com/presidio-oss/specif-ai/blob/main/CONTRIBUTING.md)  
| Before | After |
|--------|-------|
| ![before](https://github.com/user-attachments/assets/d031c0b2-5486-470e-9 …
=> feat(select): add clear button to select component

electron/mcp/mcp-connection.ts, electron/package-lock.json, electron/package.json
uses shell-path to load PATH env variable from default shell
=> fix: use shell-path to load PATH env variable from default shell

electron/agentic/react-agent/index.ts, electron/agentic/react-agent/nodes.ts
pass tools to summary call in react agent
=> fix: pass tools to summary call in react agent

.changeset/cute-papers-repair.md, electron/agentic/common/types.ts, electron/agentic/create-solution-workflow/prompts/research-information.ts, electron/agentic/create-solution-workflow/prompts/utils.ts, electron/agentic/create-solution-workflow/utils.ts, electron/api/solution/create.ts, electron/prompts/solution/create-brd.ts, electron/prompts/solution/create-nfr.ts, electron/prompts/solution/create-prd.ts, electron/prompts/solution/create-uir.ts, electron/schema/solution/create.schema.ts, ui/src/app/model/interfaces/projects.interface.ts, ui/src/app/pages/create-solution/create-solution.component.html, ui/src/app/pages/create-solution/create-solution.component.ts, ui/src/app/store/projects/projects.state.ts
This PR updates the requirement generation logic by replacing the previously used **maximum requirement count** with a **minimum requirement count**. This change ensures that a minimum number of requirements must be generated, allowing for more flexible and accurate control over requirement thresholds.
-   [ ] 🐛 Bug fix (non-breaking change which fixes an issue)  
-   [x] ✨ New feature (non-breaking change which adds functionality)  
-   [x] I have reviewed [contributor guidelines](https://github.com/presidio-oss/specifai/blob/main/CONTRIBUTING …
=> feat: switch from max to min requirement count in requirement generation

ui/package-lock.json, ui/package.json, ui/src/app/services/spreadsheet.service.ts
This PR addresses critical security vulnerabilities by replacing the xlsx module with ExcelJS in the SpreadsheetService. The current xlsx module has multiple high-severity security issues:
1. High Severity Security Issues in xlsx:
- Prototype Pollution vulnerability (GHSA-4r6h-8v6p-xvw6)
- Regular Expression Denial of Service (ReDoS) vulnerability (GHSA-5pgg-2g8v-p4x9)
Changes made:
- Replaced vulnerable xlsx module with secure ExcelJS library
=> feat: replace xlsx with exceljs for spreadsheet export functionality

.changeset/rude-dolls-pump.md, electron/agentic/suggestion-workflow/nodes.ts, electron/agentic/suggestion-workflow/types.ts, electron/agentic/task-workflow/nodes.ts, electron/agentic/task-workflow/types.ts, electron/agentic/user-story-workflow/nodes.ts, electron/agentic/user-story-workflow/types.ts, electron/api/core/get-suggestions.ts, electron/api/feature/story/add.ts, electron/api/feature/story/create.ts, electron/api/feature/story/update.ts, electron/api/feature/task/add.ts, electron/api/feature/task/create.ts, electron/api/feature/task/update.ts, electron/api/requirement/add.ts, electron/api/requirement/business-process/add.ts, electron/api/requirement/business-process/update.ts, electron/api/requirement/update.ts
This PR introduces a new configuration option `sendMessagesInTelemetry` to the workflow settings. When enabled, this flag allows telemetry data.
=> feat: add sendMessagesInTelemetry option to workflow configurations

electron/app.ts, electron/preload.ts, ui/src/app/components/layout/header/header.component.html, ui/src/app/components/layout/header/header.component.ts, ui/src/app/electron-bridge/electron.interface.ts, ui/src/app/electron-bridge/electron.service.ts
This PR fixes a UI issue where the header retained unnecessary left padding when the Electron app was in fullscreen mode. This padding caused the breadcrumbs and traffic lights to be misaligned from the screen edge. 
-   [x] 🐛 Bug fix (non-breaking change which fixes an issue)  
-   [ ] ✨ New feature (non-breaking change which adds functionality)  
-   [x] I have reviewed [contributor guidelines](https://github.com/presidio-oss/specif-ai/blob/main/CONTRIBUTING.md)  
https://github.com/user-attachments/assets/86dc41d0-bdaf-4536-94b3-3675b53dc789 …
=> fix(ui): remove left padding in fullscreen mode to align header with screen edge

electron/file-system.utility.ts, ui/src/app/components/document-listing/document-listing.component.ts, ui/src/app/model/interfaces/IList.ts, ui/src/app/store/projects/projects.state.ts
This PR addresses a bug where the "Regenerate BP" functionality failed due to incomplete metadata being read from BP files. It ensures proper extraction and mapping of `selectedBRDs`, `selectedPRDs`, and other related fields, enabling the Business Process Flow to function as intended.
- BulkReadFiles was only reading `title` and `requirement` fields from BP files
- `selectedBRDs` and `selectedPRDs` arrays were missing from the extracted data
- Business Process Flow component couldn't access the complete requirement information
- Flow chart generation was failing due to missing selected requirements data
Enhanced the file reading system to extract complete BP file metadata:
- Extended `FileChunk` type to include:
- `selectedBRDs?: Array<ISelectedRequirement>`
- `selectedPRDs?: …
=> Fix: Regenerate Business Process Functionality

ui/src/app/integrations/jira/jira.service.ts, ui/src/app/model/interfaces/Jira.ts
-   This fix resolves task-related functionality issues in the JIRA integration, where operations were failing due to
Incorrect field references.
=> fix: replaced subTaskTicketId with pmoId in JIRA integration

.changeset/heavy-impalas-add.md, ui/src/app/components/pmo-integration-modal/pmo-integration-modal.component.ts, ui/src/app/integrations/ado/ado.service.ts, ui/src/app/integrations/jira/jira.service.ts
Fixes two issues in PMO integration services:
1. **Pagination bug**: `hasMoreItems` calculation used page count instead of actual item count, causing incomplete imports
2. **ID duplication**: User story and task IDs reset per PRD instead of incrementing globally
**Root cause**: ID counters were scoped per-PRD processing loop instead of globally across all imports.
**Solution**: 
- Move ID counter initialization outside PRD loop
- Updated `formatFeaturesForPrd()` method with global counter parameters
- Fix pagination logic to track actual vs total items
closes #360 
-   [ ] 💥 Breaking change (fix or feature that would cause existing functionality to not work as …
=> fix: resolve pagination and ID duplication in PMO integrations
